spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Renuka@123
#spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8082

# Optional: JPA/Hibernate configurations

spring.jpa.show-sql=true

jwt.secret=mysecretkey
jwt.expiration=3600000